### ISSUE TITLE
How I set invoice status paid 

### ISSUE THREAD

**Issue by Jaswant0039** [Sage/sageone_api_csharp_sample#14]
Hello Sir
 I am using following code please help me update status of invoice. 
List<KeyValuePair<string, string>> postData = new List<KeyValuePair<string, string>>();

        postData.Add(new KeyValuePair<string, string>("sales_invoice[contact_id]", contact_id));
        postData.Add(new KeyValuePair<string, string>("sales_invoice[contact_name]", contact_name));
        postData.Add(new KeyValuePair<string, string>("sales_invoice[date]", date));
        postData.Add(new KeyValuePair<string, string>("sales_invoice[due_date]", due_date));
        postData.Add(new KeyValuePair<string, string>("sales_invoice[main_address]", main_address));
        postData.Add(new KeyValuePair<string, string>("sales_invoice[carriage_tax_code_id]", "1"));
      

        int count = 0;
        if (record.Count > 0)
        {                       
            foreach (Model.SageInvoice records in record)
            {
                string index = "sales_invoice[line_items_attributes][" + count.ToString() + "][";
                postData.Add(new KeyValuePair<string, string>(index + "description]", records.Description));
                postData.Add(new KeyValuePair<string, string>(index + "quantity]", records.Quantity.ToString()));
                postData.Add(new KeyValuePair<string, string>(index + "unit_price]", records.Amount.ToString()));
                postData.Add(new KeyValuePair<string, string>(index + "tax_code_id]", "5"));
                postData.Add(new KeyValuePair<string, string>(index + "ledger_account_id]", "45010442"));
                count++;
            }
        }

**Comment by cpetschnig** [comment]
Changing the status of an invoice directly is very limited. You can do a `POST /(sales|purchase)_invoices/{key}/release` to change from `DRAFT` or `PRO_FORMA` to `UNPAID`. With a `DELETE /(sales|purchase)_invoices/{key}` you can change it to `VOID`. For all other changes (`PART_PAID`, `PAID`), you have to record payments against it.

**Comment by NucsuM** [comment]
This Issue relates to a code base that is no longer used.

If somebody of you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
