### ISSUE TITLE
Getting Error Refresh token

### ISSUE THREAD

**Issue by Jaswant0039** [Sage/sageone_api_csharp_sample#15]
Hello Sir/Madam

I have used following uri when using PostRequest from RequestHelper class then getting this error "Sorry about this - It looks like we're experiencing a technical problem."
https://app.sageone.com/oauth2/token

Regards,

**Comment by timlapluie** [comment]
Hi @Jaswant0039,

`PostRequest` is not meant to be used to do the auth requests for getting an access token. Please have a look into [SageOneOAuth.cs](https://github.com/Sage/sageone_api_csharp_sample/blob/v3/Sage%20One%20Authorisation%20Client/SageOneOAuth.cs) to get an auth token.

I hope this helps.

**Comment by NucsuM** [comment]
This Issue relates to a code base that is no longer used.

If somebody of you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
