### ISSUE TITLE
Where do I find the Signing Secret used in the Master project

### ISSUE THREAD

**Issue by vaibhavghevde** [Sage/sageone_api_csharp_sample#16]
Please find the attached the below image for your reference.

![image](https://user-images.githubusercontent.com/52920073/61271130-62d28000-a7c1-11e9-9462-26da6659715b.png)

**Comment by timlapluie** [comment]
Hi @vaibhavghevde,
thanks for reaching out to us!

I could tell you that you can find your signing secret right within your registered client application on developers.sageone.com, but if you are using API v3, it is not needed anymore and you can leave it as it is in the code because we do not check it anymore.

Please make sure you use the [v3 branch](https://github.com/Sage/sageone_api_csharp_sample/tree/v3) of this sample application.

Hope that helps.

**Comment by vaibhavghevde** [comment]
Hi Tim,
Thank you for your reply.
But, Now I am trying to get the Authorization code and as a response I get a HTML page that contains the below text

> Sage One is a family of online accounting and business services for small businesses. Choose your country to get started

below is my code
`SageOneWebRequest request = new SageOneWebRequest();`
` Uri url = new Uri(AuthorizationURL + "&country=US");`
`string response = request.GetData(url);`
`if (response.Length > 0){ }`

Also, Note that I am using the Master branch and API v3.1

**Comment by vaibhavghevde** [comment]
Hi,
OK, may be I was missing something, I took the whole new copy of the master project and now I get the below error:
![image](https://user-images.githubusercontent.com/52920073/61367353-0e0a3480-a8a9-11e9-91d1-666dc2d5591b.png)
I have double checked my client Id and its correct but still I get this error.

**Comment by timlapluie** [comment]
This sample application is not working with API v3.1 currently. 

We are working on updating it to be used with API v3.1 but for now, it cannot be used to do calls against API v3.1.

Please have a look at https://developer.sage.com/api/accounting/quick_start_guide/ to see the auth flow of API v3.1 done with the help of Postman. Maybe that helps you.

**Comment by vaibhavghevde** [comment]
Hi Tim,
I have changed the Sage Business Cloud Accounting account from US to UK.
and I have made the required changes to the application, but when I try to get the authorization code, the url returns the country as US.
Can you please help.

Below is my Auhtorization URL

https://www.sageone.com/oauth2/auth/central?client_id=f3c5922e36dad094c1fd&response_type=code&redirect_uri=http%3a%2f%2flocalhost%3a59793%2fCallback&scope=full_access

and below is the url I get in return

http://localhost:59793/Callback?code=60de49de2ad9b1fc39fc849d726f32b5d7879f93&country=US&state=

**Comment by timlapluie** [comment]
Hi @vaibhavghevde,
as far as I know, it is not possible to change the country of an existing Sage Accounting business. Please make sure to sign up a new UK business. Then you should see `country=uk` in the authorization response.

**Comment by NucsuM** [comment]
This Issue relates to a code base that is no longer used. Please have a log in the latest version of this sample app. This uses Docker, .net core and Sage Business cloud accounting API v3.1. 

If somebody of you have questions about the Sage Business Cloud Accounting API or want to report problems, then the [accounting api section of sagecity.com](https://www.sagecity.com/developer/accounting-api/) is the perfect place.
