### ISSUE TITLE
Api Version

### ISSUE THREAD

**Issue by madagaga** [Sage/sageone_api_csharp_sample#5]
Hi,

How can we get api version. Actually for UK version is v1 and other are v2.
But, when I send a request to v1 (for uk test) resources are empty, and for the same site v2 contains data.

Is v1 actually deprecated ?

**Comment by timlapluie** [comment]
Hi @madagaga,

if you want to develop against Sage One, please use the latest version of the API, which is `v3`. It has a lot more endpoints to retrieve more data from Sage One than `v1` and `v2`. 
You'll find all needed documentation here: https://developer.columbus.sage.com/docs#/uki/sageone/accounts.

You can use the `sageone_api_csharp_sample` for `v3` as well, just check out the branch named `v3` of this repository.
