### ISSUE TITLE
Can we integrate it without the help of browser. Just like using secret keys of the app

### ISSUE THREAD

**Issue by corientdev** [Sage/sageone_api_csharp_sample#7]
Can we integrate it without the help of browser. Just like using secret keys of the app?
Because we are aiming for windows app which will be posting entries without opening browser for auth

**Comment by timlapluie** [comment]
Hi @corientdev and thanks for your question!
Because of the OAuth2 process, every user of your client needs to grant access rights to access his data from a client. There is no way to do this e.g. with a secret key.
It should be possible to use a browser component in your C# app directly to display the grant access page without opening a dedicated web browser.

**Comment by corientdev** [comment]
How to raise Purchase invoice? There is no class for it in lib?

**Comment by cpetschnig** [comment]
Apologies, this lib is meant to get you quickly going, but it's by no means a full-grown SDK. I fear you have to write your own class.

**Comment by corientdev** [comment]
how it can be done? like flow or something. because if i run the sample it shows error page while going for oauth

**Comment by timlapluie** [comment]
Please have a look at https://developers.sageone.com/, you will find a documentation on how to connect with the Sage One API. 
Also, you have to use the `v3` branch of this sample application to use it with the latest API version.

**Comment by corientdev** [comment]
already did it but basic example is not working
![dfgdfgg](https://cloud.githubusercontent.com/assets/9655234/26409481/47f95220-40be-11e7-8658-3da220263be3.png)

seee this and also would like to tell you as a feedback that it is too difficult to integrate with sageone than any other software since i have made bridge to many well known accounting softwares

**Comment by Pete-Brown** [comment]
Hi

That suggests you have not entered your client_id or redirect_uri into sageone_api_csharp_sample/Sage One Authorisation Client/SageOneOAuth.cs exactly as they appear in the application you have registered at https://developers.sageone.biz/applications

Can you check that the values you have added to the file match exactly? That you have exactly the same case for the callback url?

**Comment by corientdev** [comment]
request `{
  "contact": {
    "name": "Vishal2",
    "contact_type_ids": [
      "string"
    ],
    "transaction_id": "string",
    "reference": "string",
    "default_sales_ledger_account_id": "string",
    "default_sales_tax_rate_id": "string",
    "default_purchase_ledger_account_id": "string",
    "tax_number": "string",
    "notes": "string",
    "locale": "string",
    "credit_limit": 0.0,
    "credit_days": 0,
    "credit_terms_and_conditions": "string",
    "product_sales_price_type_id": "string",
    "source_guid": "string",
    "currency_id": "string",
    "aux_reference": "string",
    "registered_number": "string",
    "deletable": true,
    ,
      "name": "string",
      "job_title": "string",
      "telephone": "string",
      "mobile": "string",
      "email": "string",
      "fax": "string",
      "is_main_contact": true,
      "address_id": "string"
    },
    "bank_account_details": {
      "account_name": "string",
      "account_number": "string",
      "sort_code": "string",
      "bic": "string",
      "iban": "string"
    }
  }
}`

response `[
  "Sorry about this - It looks like we're experiencing a technical problem."
]`
endpoint `contacts`

get works fine but post gives the above error

**Comment by Pete-Brown** [comment]
Can you test with the following post data:
`
{
  "contact": {
    "name": "Foo Bar",
    "contact_type_ids": [
      "CUSTOMER"
    ]
  }
}
`

Anything with an id will need to use a valid id for the business.

**Comment by corientdev** [comment]
Works brilliantly.. I was wondering.. Why it is not documented?On May 24, 2017 9:01 PM, Pete-Brown <notifications@github.com> wrote:Can you test with the following post data:
{ "contact": { "name": "Foo Bar", "contact_type_ids": [ "CUSTOMER" ] } }

**Comment by Pete-Brown** [comment]
This page documents the required fields for POST on the contacts endpoint:

https://developer.columbus.sage.com/docs#/uki/sageone/accounts/v3/contacts_contact

**Comment by corientdev** [comment]
Thank you for this but i believe this link is not easy to find.. and yes in sample code it goes to `gb` instead of `uki`

**Comment by corientdev** [comment]
`{
  "purchase_invoice": {
    "contact_id": "7a579af0409611e797950a57719b2edb",
    "date": "26-03-2017",
    "due_date": "28-03-2017",
    "invoice_lines": {
      "description": [
        "Test Description"
      ],
      "ledger_account_id": [
        "fc92638b3fc611e797950a57719b2edb"
      ],
      "quantity": [
1.0
      ],
      "unit_price": [
        10.0
      ]
      
    }
  }
}`

my json for purchase invoice post

error

`[
  {
    "$severity": "error",
    "$dataCode": "Validation",
    "$message": "purchase_invoice[invoice_lines] is invalid",
    "$source": "purchase_invoice[invoice_lines]"
  },
  {
    "$severity": "error",
    "$dataCode": "Validation",
    "$message": "purchase_invoice[invoice_lines] is invalid",
    "$source": "purchase_invoice[invoice_lines]"
  },
  {
    "$severity": "error",
    "$dataCode": "Validation",
    "$message": "purchase_invoice[invoice_lines] is invalid",
    "$source": "purchase_invoice[invoice_lines]"
  },
  {
    "$severity": "error",
    "$dataCode": "Validation",
    "$message": "purchase_invoice[invoice_lines][0][description] is invalid",
    "$source": "purchase_invoice[invoice_lines][0][description]"
  },
  {
    "$severity": "error",
    "$dataCode": "Validation",
    "$message": "purchase_invoice[invoice_lines][0][ledger_account_id] is invalid",
    "$source": "purchase_invoice[invoice_lines][0][ledger_account_id]"
  },
  {
    "$severity": "error",
    "$dataCode": "Validation",
    "$message": "purchase_invoice[invoice_lines][0][quantity] is invalid",
    "$source": "purchase_invoice[invoice_lines][0][quantity]"
  },
  {
    "$severity": "error",
    "$dataCode": "Validation",
    "$message": "purchase_invoice[invoice_lines][0][unit_price] is invalid",
    "$source": "purchase_invoice[invoice_lines][0][unit_price]"
  }
]`

**Comment by Pete-Brown** [comment]
You have formatted the JSON incorrectly. See the documentation:

https://developer.columbus.sage.com/docs#/uki/sageone/accounts/v3/purchase_invoices_purchase_invoice

If you are posting to UKI, you do not need the tax_address_region_id, so

```
{
  "purchase_invoice": {
    "contact_id": "0b47c0ba60a88bd00b199158272sGBP",
    "date": "2016-01-01",
    "due_date": "2016-02-01",
    "reference": "INV0001",
    "vendor_reference": "The Vendor Reference",
    "notes": "Some notes about the invoice",
    "exchange_rate": 0.5,
    "invoice_lines": [
      {
        "product_id": "0c47c0pr0188bd00b199158272d678",
        "description": "Line 1",
        "ledger_account_id": "0c47c0cc60a88bd00b199158272d678",
        "quantity": 2,
        "unit_price": 50,
        "tax_rate_id": "0b47c0cc60a88bd00b199158272tr20",
        "tax_amount": 20
      },
      {
        "product_id": "0c47c0pr0188bd00b199158272d678",
        "description": "Line 2",
        "ledger_account_id": "0c47c0cc60a88bd00b199158272d678",
        "quantity": 2,
        "unit_price": 50,
        "tax_rate_id": "0b47c0cc60a88bd00b199158272tr20",
        "tax_amount": 20
      }
    ]
  }
}
```

**Comment by corientdev** [comment]
i saw this from here `https://developer.columbus.sage.com/docs/services/57c9493f00c9d3171caa8dcb/operations/57ee79b200c9d302b8f2b4ec/console`

its bit confusing

**Comment by Pete-Brown** [comment]
It will be better to raise any further support requests with the support team:

sageonedevelopers@sage.com

**Comment by corientdev** [comment]
Yes My question is yet not answered i am sorry. Can we build some kind of Windows form app or console app without callback url.?

**Comment by corientdev** [comment]
Do we have some kind of Private authenticator for sageone? just like xero [https://github.com/XeroAPI/Xero-Net#privateauthenticator](https://github.com/XeroAPI/Xero-Net#privateauthenticator) There is `PrivateAuthenticator` which doesn't require token

**Comment by Pete-Brown** [comment]
Please see the second reply in this thread:


Hi @corientdev and thanks for your question!
Because of the OAuth2 process, every user of your client needs to grant access rights to access his data from a client. There is no way to do this e.g. with a secret key.
It should be possible to use a browser component in your C# app directly to display the grant access page without opening a dedicated web browser.

**Comment by corientdev** [comment]
it is possible to do it without callback url?

I mean i am not getting it because in windows app there is no call back url at all. and without call back url we can't access the token page i believe

**Comment by Pete-Brown** [comment]
No, you would need a local address for the callback.
